# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIX7oP7ZxN8RLmEZFYdnfNS5KOeJliuN
"""

#programa que calcula el indice de masa corporal de una persona

peso=float(input("Ingrese aqui su peso en kilogramos: "))
estatura=float(input("ingrese aqui su estatura en metros: "))

indice= (peso)/(estatura**2)

print("su indice de masa corporal es: ", round(indice,2))